name: PCBridge
main: com.pcb.pcbridge.PCBridge
version: 0.2.1
depend: [Vault]
softdepend: [PermissionsEx]

commands:
  ban:
    description: Permanently bans the specified player from the server.
    usage: /<command> [player] [reason]
    permission: pcbridge.ban.ban
  unban:
    description: Unbans the specified player.
    usage: /<command> [player]
    permission: pcbridge.ban.unban
  lookup:
    description: Checks if the specified player is currently banned.
    usage: /<command> [player]
    permission: pcbridge.ban.lookup
  tempban:
    description: Temporarily bans the specified player from the server.
    usage: /<command> [player] [time][m|h|d|w|mo|y] [reason]
    permission: pcbridge.ban.tempban
  uuid:
    description: Retrieves UUID data about a player from Mojang's web service
    usage: /<command> [history|uuid] [player]
    permission: pcbridge.ban.uuid
  pcbridge:
    description: Config and settings for the PCBridge plugin
    usage: /<command> config [key] [on|off]
    permission: pcbridge.utility
  swearblock:
    description: Toggles on/off the chat swear filter
    usage: /<command>
    permission: pcbridge.swearblock.toggle