name: PCBridge
main: com.pcb.pcbridge.PCBridge
version: 0.0.1

commands:
  ban:
    description: This is a demo command.
    usage: /<command> [player] [reason]
    permission: <plugin name>.basic
    permission-message: You don't have <permission>
  unban:
    description: This is a demo command.
    usage: /<command> [player]
    permission: <plugin name>.basic
    permission-message: You don't have <permission>
  checkban:
    description: This is a demo command.
    usage: /<command> [player]
    permission: <plugin name>.basic
    permission-message: You don't have <permission>